services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
    env_file:
      - ./auth-service/.env
    ports:
      - "8001:8000"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      orders-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=orders-db
      - DB_PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS_HOST=kafka
      - KAFKA_BOOTSTRAP_SERVERS_PORT=9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./order-service/.env
    ports:
      - "8002:8000"

  auth-db:
    image: postgres:18-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
      POSTGRES_DB: ${DB_NAME:-auth}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres_data_auth:/var/lib/postgresql

  orders-db:
    image: postgres:18-alpine
    container_name: orders-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-admin}
      POSTGRES_DB: ${DB_NAME:-orders}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres_data_orders:/var/lib/postgresql

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      # Параметры для KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      # Настройка разных слушателей
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9094:9094"
    volumes:
      - ./data/kafka_data:/var/lib/kafka/data

  kafka-topics:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-topics
    user: root
    depends_on:
      - kafka
    volumes:
      - ./kafka-topics.sh:/kafka-topics.sh
    entrypoint: ["/bin/sh", "/kafka-topics.sh"]
    environment:
      BOOTSTRAP_SERVER: kafka:9092

  redis:
    image: redis:8.6-alpine
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLID: 'true'

volumes:
  postgres_data_auth:
  postgres_data_orders:
  kafka_data: